language: cpp

compiler:
  - gcc
  - clang

install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq libopencv-dev

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
